IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'STAGE')
    EXEC('CREATE SCHEMA STAGE');
GO

IF OBJECT_ID('STAGE.Airline') IS NOT NULL DROP TABLE STAGE.Airline;
CREATE TABLE STAGE.Airline (
    IATA_CODE   VARCHAR(10) NULL,
    AIRLINE     VARCHAR(255) NULL
)
