CREATE DATABASE State;
GO

USE State;
IF OBJECT_ID('Flights', 'U') IS NOT NULL

CREATE TABLE Flights (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    [DATE] DATE,
    AIRLINE NVARCHAR(10),
    FLIGHT_NUMBER NVARCHAR(10),
    TAIL_NUMBER NVARCHAR(10),
    ORIGIN_AIRPORT NVARCHAR(10),
    DESTINATION_AIRPORT NVARCHAR(10),
    SCHEDULED_DEPARTURE TIME,
    DEPARTURE_TIME TIME,
    DEPARTURE_DELAY INT,
    TAXI_OUT INT,
    WHEELS_OFF TIME,
    SCHEDULED_TIME INT,
    ELAPSED_TIME INT,
    AIR_TIME INT,
    DISTANCE INT,
    WHEELS_ON TIME,
    TAXI_IN INT,
    SCHEDULED_ARRIVAL TIME,
    ARRIVAL_TIME TIME,
    ARRIVAL_DELAY INT,
    DIVERTED BIT,
    CANCELLED BIT,
    CANCELLATION_REASON NVARCHAR(10),
    AIR_SYSTEM_DELAY INT,
    SECURITY_DELAY INT,
    AIRLINE_DELAY INT,
    LATE_AIRCRAFT_DELAY INT,
    WEATHER_DELAY INT,
    CREATED DATETIME DEFAULT GETDATE(),
    MODIFIED DATETIME DEFAULT GETDATE()
);
GO