use master
DROP DATABASE IF EXISTS Project_Stage_DB;
go

create database Project_Stage_DB
go
use Project_Stage_DB
go


IF OBJECT_ID('Stage_Airline') IS NOT NULL DROP TABLE Stage_Airline;
CREATE TABLE Stage_Airline (
    IATA_CODE   CHAR(2) NULL,
    AIRLINE     VARCHAR(200) NULL
)

IF OBJECT_ID('Stage_Airport') IS NOT NULL DROP TABLE Stage_Airport;
CREATE TABLE Stage_Airport (         
    IATA_CODE   CHAR(3) NULL,
    AIRPORT     VARCHAR(200) NULL,
    CITY        VARCHAR(100) NULL,
    STATE       VARCHAR(100) NULL,
    COUNTRY     VARCHAR(100) NULL,
    LATITUDE    DECIMAL(9,6) NULL,
    LONGITUDE   DECIMAL(9,6) NULL
)


IF OBJECT_ID('Stage_Flight') IS NOT NULL DROP TABLE Stage_Flight;
CREATE TABLE Stage_Flight (
    SourceFile_ID INT, -- 1, 2, 3
    DATE DATE,
    AIRLINE CHAR(2),
    FLIGHT_NUMBER VARCHAR(10),
    TAIL_NUMBER VARCHAR(10),
    ORIGIN_AIRPORT CHAR(3),
    DESTINATION_AIRPORT CHAR(3),
    SCHEDULED_DEPARTURE VARCHAR(10) NULL,
    DEPARTURE_TIME VARCHAR(10) NULL,
    DEPARTURE_DELAY INT,
    TAXI_OUT INT,
    WHEELS_OFF VARCHAR(10) NULL,
    SCHEDULED_TIME INT,
    ELAPSED_TIME INT,
    AIR_TIME INT,
    DISTANCE INT,
    WHEELS_ON VARCHAR(10) NULL,
    TAXI_IN INT,
    SCHEDULED_ARRIVAL VARCHAR(10) NULL,
    ARRIVAL_TIME VARCHAR(10) NULL,
    ARRIVAL_DELAY INT,
    DIVERTED BIT,
    CANCELLED BIT,
    CANCELLATION_REASON CHAR(1),
    AIR_SYSTEM_DELAY INT,
    SECURITY_DELAY INT,
    AIRLINE_DELAY INT,
    LATE_AIRCRAFT_DELAY INT,
    WEATHER_DELAY INT,
    CREATED DATETIME,
    MODIFIED DATETIME
);


SELECT * FROM Stage_Airline;
SELECT * FROM Stage_Airport;
SELECT * FROM Stage_Flight;

/*
INSERT INTO Stage_Flight (DATE, FLIGHT_NUMBER, ORIGIN_AIRPORT, DESTINATION_AIRPORT, SCHEDULED_DEPARTURE)
VALUES ('2025-01-01', 1103, 'LGA', 'DFW', NULL);
*/