IF OBJECT_ID('STAGE.Airport') IS NOT NULL DROP TABLE STAGE.Airport;
CREATE TABLE STAGE.Airport (
    Row_ID      INT NULL,            
    IATA_CODE   VARCHAR(10) NULL,
    AIRPORT     VARCHAR(255) NULL,
    CITY        VARCHAR(100) NULL,
    STATE       VARCHAR(10) NULL,
    COUNTRY     VARCHAR(50) NULL,
    LATITUDE    DECIMAL(9,6) NULL,
    LONGITUDE   DECIMAL(9,6) NULL
)