use master
DROP DATABASE IF EXISTS Project_Stage_DB;
go

create database Project_Stage_DB
go
use Project_Stage_DB
go


IF OBJECT_ID('Stage_Airline') IS NOT NULL DROP TABLE Stage_Airline;
CREATE TABLE Stage_Airline (
    IATA_CODE   VARCHAR(10) NULL,
    AIRLINE     VARCHAR(255) NULL
)

IF OBJECT_ID('Stage_Airport') IS NOT NULL DROP TABLE Stage_Airport;
CREATE TABLE Stage_Airport (         
    IATA_CODE   VARCHAR(10) NULL,
    AIRPORT     VARCHAR(255) NULL,
    CITY        VARCHAR(100) NULL,
    STATE       VARCHAR(10) NULL,
    COUNTRY     VARCHAR(50) NULL,
    LATITUDE    DECIMAL(9,6) NULL,
    LONGITUDE   DECIMAL(9,6) NULL
)


IF OBJECT_ID('Stage_Flight') IS NOT NULL DROP TABLE Stage_Flight;
CREATE TABLE Stage_Flight (
    DATE DATE,
    AIRLINE VARCHAR(10),
    FLIGHT_NUMBER VARCHAR(10),
    TAIL_NUMBER VARCHAR(10),
    ORIGIN_AIRPORT VARCHAR(10),
    DESTINATION_AIRPORT VARCHAR(10),
    SCHEDULED_DEPARTURE TIME,
    DEPARTURE_TIME TIME,
    DEPARTURE_DELAY INT,
    TAXI_OUT INT,
    WHEELS_OFF TIME,
    SCHEDULED_TIME INT,
    ELAPSED_TIME INT,
    AIR_TIME INT,
    DISTANCE INT,
    WHEELS_ON TIME,
    TAXI_IN INT,
    SCHEDULED_ARRIVAL TIME,
    ARRIVAL_TIME TIME,
    ARRIVAL_DELAY INT,
    DIVERTED BIT,
    CANCELLED BIT,
    CANCELLATION_REASON CHAR(1),
    AIR_SYSTEM_DELAY INT,
    SECURITY_DELAY INT,
    AIRLINE_DELAY INT,
    LATE_AIRCRAFT_DELAY INT,
    WEATHER_DELAY INT,
    CREATED DATETIME,
    MODIFIED DATETIME
);


SELECT * FROM Stage_Airline;
SELECT * FROM Stage_Airport;
SELECT * FROM Stage_Flight;